name: Test

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      # We can't use -slim because we need Git
      image: node:18.17.0
    timeout-minutes: 3

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Add private SSH key for cloning other repos
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.CI_SSH_PRETTIER_CONFIG_PDC }}

      - name: Cache dependencies
        uses: actions/cache@v3
        env:
          cache-name: npm
        with:
          path: ~/.npm
          key: ${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ env.cache-name }}-

      - name: Print versions
        run: |
          node --version
          npm --version

      - name: Install dependencies
        run: npm install --prefer-offline

      - name: Run ESLint and Prettier
        run: npm run lint
